---
default:
  image: registry.gitlab.com/oliver.cutting/deploy-app-to-aws:latest

stages:
  - test

yamllint:
  stage: test
  allow_failure: true
  script:
    - yamllint .

terraform-lint:
  stage: test
  allow_failure: true
  script:
    - terraform init
    - terraform fmt -diff -recursive -check || (terraform fmt -recursive && exit 1)
    - terraform validate

kics-scan:
  stage: test
  allow_failure: true
  image: 
    name: checkmarx/kics:latest
    entrypoint: [""]
  script:
    - kics scan --no-progress -p ${PWD} -o ${PWD} --report-formats json --output-name kics-results
  artifacts:
    name: kics-results.json
    paths:
      - kics-results.json
    when: always
